oshc/authentication/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/login/profile/', views.profile, name="profile"),
    url(r'^ajax/validate_username/$',
        views.validate_username,
        name='validate_username'),
]

oshc/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^about/', views.about, name="about"),
    url(r'^session/', views.request_session, name="request_session"),
    url(r'^contests/', views.contests, name="contests"),
    url(r'^contest_new/', views.contest_new, name="contest_new"),
    url(r'^add_contest/', views.add_contest, name="add_contest"),
    url(r'^submit_contest/', views.submit_contest, name="submit_contest"),
    url(r'^chatsessions/', views.chat_sessions, name="chat_sessions"),
    url(r'^opensourceday/', views.opensourceday, name="opensourceday"),
    url(r'^jobs/', views.jobs, name="jobs"),
]

oshc/oshc/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
    url(r'', include('authentication.urls')),
]

oshc/main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class chatSession(models.Model):
<<<<<<< issue1
    name = models.CharField(max_length=128, help_text="Session title")
    link = models.URLField(help_text="Chat session URL")
    profile_name = models.CharField(max_length=128,
                                    help_text="The person's name")
    profile_url = models.URLField(help_text="The Url of the person's website")
    description = models.TextField(max_length=512, help_text="Session details")
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    link = models.URLField(help_text="Chat session URL")

    def __str__(self):
        return self.name


class Contest(models.Model):
    name = models.CharField(max_length=128, help_text="Contest name")
    link = models.URLField(help_text="URL of the contest's website")
    description = models.TextField(
        max_length=512, help_text="Contest details", null=True)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Journey(models.Model):
    title = models.CharField(max_length=128, help_text="Journey title")
    start_date = models.DateField(null=True)

    def __str__(self):
        return self.title

oshc/main/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from .models import Contest


class ContestForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ContestForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.fields['start_date'].widget.attrs['class'] = 'datepicker'
        self.fields['end_date'].widget.attrs['class'] = 'datepicker'

    class Meta:
        model = Contest
        fields = ['name', 'link', 'description', 'start_date', 'end_date']

oshc/authentication/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.http import JsonResponse


def profile(request):
    return render(request, "profile.html")


def validate_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_present': User.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(data)

oshc/main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.models import chatSession, Contest, Journey
from .forms import ContestForm


def home(request):
    # chat_session_list = chatSessions.objects.order_by('start_date')[:3]
    # context_dict = {'chatSessions': chat_session_list}
    return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')


def request_session(request):
    return render(request, 'session.html')


def contests(request):
    contest_list = Contest.objects.all()
    return render(
        request, 'contests.html', context={
            'contest_list': contest_list
        })


def contest_new(request):
    form = ContestForm()
    return render(request, 'contest_edit.html', {'form': form})


def add_contest(request):
    if request.method == 'POST':
        form = ContestForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/submit_contest/")
    else:
        form = ContestForm()
    return render(request, 'contest_edit.html', {'form': form})


def submit_contest(request):
    return render(request, 'contest_submission.html')

def chat_sessions(request):
    chat_session_list = chatSession.objects.all()
    return render(request, 'chatsessions.html',
                  context={'chat_session_list': chat_session_list})


def handler404(request):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response

def opensourceday(request):
    opensourceday_list = OpenSourceDay.objects.order_by('start_date')
    return render(request, 'opensourceday.html', context={'OpenSourceDay': opensourceday_list})
  
def jobs(request):
    return render(request, 'jobs.html')

oshc/main/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="main-section">
	<div class="container">
			<h1>About <i class="fa fa-users"></i></h1>
	</div>
</section>
{% endblock %}

oshc/main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  {% include 'header.html' %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> {% if site.title %}
  <title>
    {% if title %} {{ title }} &ndash; {% endif %} {{ site.title }} {% if not title and site.subtitle %} &ndash; {{ site.subtitle }} {% endif %}
  </title>
  {% endif %}
</head>

<body>
  <nav class="navbar navbar-inverse navbar-static-top navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        <a class="navbar-brand" href="{% url 'home' %}">Open Source Help Community</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sessions <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
							<li><a href="{% url 'chat_sessions' %}" target="_blank">View Session</a></li>
              <li><a href="{% url 'request_session' %}" target="_blank">Request a Session</a></li>
            </ul>
          </li>
          <li><a href="https://github.com/OpenSourceHelpCommunity" target="_blank">Resources</a></li>
          <li><a href="{% url 'contests' %}">Contests</a></li>
          <li><a href="https://opensourcehelp.herokuapp.com/" target="_blank">Join Us!</a></li>
          {% if user.is_authenticated %}
          <li><a href="#!">Hey {{ user.username }}!</a></li>
          <li><a href="{% url 'account_logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'account_login' %}">Sign In</a></li>
          <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div>
    {% block content %}{% endblock %}
  </div>

  {% block footer %}
  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="social">
            <ul>
              <span class="col-sm-6 left-align">
								<li>
									<a href="https://www.facebook.com/opensourcehelpcommunity/" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
								</li>
								<li>
									<a href="https://twitter.com/oshelpcommunity" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
								</li>
								<li>
									<a href="https://github.com/OpenSourceHelpCommunity" target="_blank"><i class="fa fa-github" aria-hidden="true"></i></a>
								</li>
		      						<li>
									<a href="{% url 'opensourceday' %}"><i class="fa fa-users" aria-hidden="true"></i></a>
		      						</li>
								<li>
									<a href="https://www.youtube.com/channel/UC1_IAby-9me3iICtxuiDL5Q" target="_blank"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
								</li>
                <li>
									<a href="https://opensourcehelp.herokuapp.com/" target="_blank"><i class="fa fa-slack" aria-hidden="true"></i></a>
								</li>
                <li>
                  <a href="mailto:opensourcehelpcommunity@gmail.com" target="_blank"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                </li>
							</span>
              <span class="col-sm-6 back-to-top right-align">
								<a id="toTop" name="Back to top!">Back to top</a>
							</span>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-xs-12">
        <div class="copyright">
          &copy; 2017 Open Source Help Community
        </div>
      </div>
    </div>
  </footer>
  {% endblock %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="{% static "main/js/script.js" %}"></script>
  {% block javascript %}{% endblock %}
</body>

</html>

oshc/main/templates/chatsessions.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
h3 {
    text-align: center;
}
span
{
    display: block;
}
</style>
<section class="main-section">
	<div class="container">
            <h3>Open Source Contributors Chat Sessions</h3>
            <div class="container-fluid">
                <div class="row">
                    {% for chat_session in chat_session_list %}
                        {% if chat_session.approved %}
                            <div class="col-lg-4">
                                <div class="panel panel-default">
                                    <div class="panel-heading" style="background-color: #0275d8;color:white">{{chat_session.name}}</div>
                                    <div class="panel-body">
																			<span><i class="fa fa-youtube"></i> <a href="{{chat_session.link}}">{{chat_session.link}}</a></span>
                                        <span><i class="fa fa-clock-o"></i> {{chat_session.start_date}}</span>
                                        <span><i class="fa fa-info-circle"></i> {{chat_session.description}}</span>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
	</div>
</section>
{% endblock %}

oshc/main/templates/contest_edit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <link href="{% static 'main/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static 'main/js/moment.min.js' %}"></script>
    <script src="{% static 'main/js/bootstrap-datetimepicker.min.js' %}"></script>
    <form name="newContest" method="POST" style="margin-top:70px;" class="form-horizontal"
          action="{% url 'add_contest' %}">
        {% crispy form %}
        <div class="form-group">
            <div style="margin-bottom: 10px;" class="col-xs-offset-5 col-xs-8">
                <button type="submit" class="save btn btn-default">SUBMIT</button>
            </div>
        </div>
    </form>

    <script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(function () {
            $('.datepicker').datetimepicker(
                {
                    format: 'YYYY-MM-DD',
                }
            );
        });

        // protect against invalid time ranges
        $("#id_start_date").on("dp.change", function (e) {
            $('#id_end_date').data("DateTimePicker").minDate(e.date);
        });
    });
    </script>
{% endblock %}

oshc/main/templates/contest_submission.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="jumbotron text-xs-center">
  <div class="container text-center vcenter">
      <h1 class="display-3">Thank you!</h1>
      <p class="lead subtitle"><strong>Your contest has been submitted for review.</strong></p>
      <hr>
      <p class="lead">
        <a class="btn btn-primary btn-sm" href="{% url 'home' %}" role="button">Continue to homepage</a>
      </p>
  </div>
</div>

{% endblock %}

oshc/main/templates/contests.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
h3 {
    text-align: center;
}
span
{
    display: block;
}
</style>
<section class="main-section">
	<div class="container">
            <h3>List of Upcoming Open Source Contests</h3>
            <div class="container-fluid">
                <div class="row">
                    {% for contest in contest_list %}
                        {% if contest.approved %}
                            <div class="col-lg-4">
                                <div class="panel panel-default">
                                    <div class="panel-heading" style="background-color: #0275d8;color:white">{{contest.name}}</div>
                                    <div class="panel-body">
                                        <span><span class="glyphicon glyphicon-globe"></span> <a href="{{contest.link}}">{{contest.link}}</a></span>
                                        <span><span class="glyphicon glyphicon-time"></span> {{contest.start_date}}-{{contest.end_date}}</span>
                                        <span><span class="glyphicon glyphicon-info-sign"></span> {{contest.description}}</span>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="Button" align="center" style="margin-bottom:70px; margin-top:20px;">
                <a href="{% url 'contest_new' %}" class="btn btn-default" style="background-color:#0275d8;color:white;">Submit a New Contest</a>
            </div>
	</div>
</section>
{% endblock %}

oshc/main/templates/header.html
{% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1"> {% if site.author %}
<meta name="author" content="{{ site.author }}">{% endif %} {% if site.description %}
<meta name="description" content="{{ site.description }}">{% endif %}
<meta name="generator" content="mynt v{{ site.version }}">
<link rel="shortcut icon" href="{% static "main/images/favicon.ico" %}" type="image/x-icon">
<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700,900" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="{% static "main/css/app.css" %}" rel="stylesheet">
<script src="https://use.fontawesome.com/ae7ffc7b99.js"></script>

oshc/main/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="main-section">
	<div class="container">
		<div class="jumbotron text-center">
			<img class="logo-image img-responsive" src="{% static "main/images/oshc-logo.png"%}" alt="Open Source Help Community Logo" />
			<h1>Open Source Help Community</h1>
			<h4>A Online Platform To Help People To Start Contributing To Open Source Projects</h4>
		</div>
	</div>
</section>

<section class="section-two">
	<div class="container">
		<h3>Our Mission</h3>
		<p class="bi">
			<b>"</b>Open Source Help Community is a virtual platform to help people to start contributing to open source projects<b>"</b>
		</p>
		<p class="intro">
			OSHC is established with the idea in mind to reach those people who are interested in contributing to open source projects but find it difficult. OSHC organizes sessions with open source projects contributors and publishes material which will be useful
			for people to get started with contributing to open source projects.
		</p>
		<div class="line-gap-10px"></div>
		<p class="intro">
			If you would like to share your thoughts or your journey with us, have ideas to make this great, or have questions, please get in touch at <a href="mailto:opensourcehelpcommunity@gmail.com">opensourcehelpcommunity@gmail.com</a>
		</p>
	</div>
</section>

<section class="section-three">
	<div class="container">
		<h3>Upcoming Sessions</h3>

		<div class="row">
			<div class="col-md-7 left-session-info">
				<div class="panel panel-default">
					{% if chatSession %}
					 {% for session in chatSession %}
					<div class="panel-heading">
						<h3 class="panel-title">{{ session.title }}</h3>
					</div>
					<div class="panel-body">
						<a href="{{ session.profile_url }}">{{ session.profile_name }}</a> {{ session.description }}
						<div class="line-gap-10px"></div>
						<i>{{ session.start_date }} - {{ session.end_date }}</i>
						<div class="line-gap-10px"></div>
						<button type="button" class="btn btn-lg btn-primary sRegister">
								<a href="{{ session.register_url }}">Register Now!</a>
							</button>
					</div>
					 {% endfor %}
					{% else %}
					<strong>No session available</strong>
					{% endif %}
				</div>
			</div>

			<div class="col-md-5 left-social-section">
				<div class="twitter-feed">
					<a class="twitter-timeline" data-width="500" data-height="500" data-theme="light" data-link-color="#26A9E0" href="https://twitter.com/oshelpcommunity">
							Tweets by oshelpcommunity
						</a>
					<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
				</div>
			</div>
		</div>
	</div>
</section>


{% endblock %}

oshc/main/templates/jobs.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="timeline">
<body>
  <ul>
    {% if Jobs %}
      {% for j in Jobs %}
      <li>
      <div> {{j.start_date}}<br>{{j.title}} </div>
      </li>
    <!-- more list items here -->
      {% endfor %}
    {% else %}
      <li>
      <div> Social Media Account Coordinators </div>
	  <p> OSHC is looking for people who can handle the social media channels. Send
	  an email or drop a ping in #oshc-social-media Slack channel if interested,
	  please resort last on DMs. Few guidelines:
	  - Few to no retweets
	  - Organise chats
	  - Post essential updates
	  - You are free (aligning your posts about OSHC)

	  All applicants will be allowed to organise the channels for few days, based
	  on your work you can continue to work as social media account coordinator.

	  You'll be paid for the time you work on the channels, if you prefer goodies
	  or books please DM in Slack channel.
	  </p>
      </li>
    {% endif %}
  </ul>
</body>
</section>
{% endblock %}

oshc/main/templates/journey.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="timeline">
<body>
  <ul>
    {% if Journey %}
      {% for j in Journey %}
      <li>
      <div> {{j.start_date}}<br>{{j.title}} </div>
      </li> 
    <!-- more list items here -->
      {% endfor %}
    {% else %}
      <li>
      <div> No journey available </div>
      </li> 
    {% endif %}
  </ul>
</body>
</section>
{% endblock %}

oshc/main/templates/profile.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Profile" %}{% endblock %}

{% block content %}
<section class="main-section">
    <h1>{% trans "Welcome to Open Source Help Community" %}</h1>
</section>
{% endblock %}

oshc/main/templates/session.html
{% extends 'base.html' %} {% load static %} {% block content %}

<iframe id="typeform-full" width="100%" height="100%" frameborder="0" src="https://oshc.typeform.com/to/CvcyEy"></iframe>
<script type="text/javascript" src="https://embed.typeform.com/embed.js"></script>

{% endblock %}
<html>

oshc/templates/base.html
{% load static %}

<!DOCTYPE html>

<html>
<head>
  {% include 'header.html' %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  {% if site.title %}<title>{% if title %}{{ title }} &ndash; {% endif %}{{ site.title }}{% if not title and site.subtitle %} &ndash; {{ site.subtitle }}{% endif %}</title>{% endif %}
</head>

<body>

  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">{{ site.title }}</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/sessions/">Sessions</a></li>
            <li><a href="https://github.com/OpenSourceHelpCommunity">Resources</a></li>
            <li><a href="mailto:opensourcehelpcommunity@gmail.com">Contact</a></li>
            <li><a href="https://opensourcehelp.herokuapp.com/">Join Us!</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </div>

  <div id="content">
    {% block content %}{% endblock %}
  </div>
  <script src="http://code.jquery.com/jquery-2.0.3.min.js"></script>
  <script src="{% static "assets/js/bootstrap.js"%}"></script>


</body>
</html>

oshc/templates/header.html
{% load static %}

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% if site.author %}<meta name="author" content="{{ site.author }}">{% endif %}
{% if site.description %}<meta name="description" content="{{ site.description }}">{% endif %}
<meta name="generator" content="mynt v{{ site.version }}">

<link rel="shortcut icon" href="{% static "assets/images/favicon.ico"%}" type="image/x-icon">

<link href="{% static "assets/css/bootstrap.css"%}" rel="stylesheet">
<link href="{% static "assets/css/app.css"%}" rel="stylesheet">

oshc/templates/index.html
{% extends 'base.html' %}
{% load staticfiles%}
{% block content %}
  <div class="container">
    <div class="jumbotron text-center">
		<img id="logo" src="{% static "assets/images/oshc-logo.png"%}" alt="" >
        <h1>Open Source Help Community</h1>
        <h3>A Virtual Platform To Help People To Start Contributing To Open Source Projects.</h3>
    </div>
  </div>


  <div class="container marketing">

    <div class="row">

      <div class="col-sm-8">
        <h2>Our Mission</h2>
		<p>Open Source Help Community is an a virtual platform to help people to start contributing to open source projects.</p>      <p>OSHC is established with the idea in mind to reach those people who are interested in contributing to open source projects but find it difficult. OSHC organizes sessions with open source projects contributors and publishes material which will be useful for people to get started with contributing to open source projects.</p>
        <p>If you would like to share your thoughts or your journey with us, have ideas to make this great, or have questions, please get in touch at <a href="mailto:opensourcehelpcommunity@gmail.com">opensourcehelpcommunity@gmail.com</a>.</p>
		<h2>Recent Tweets <img src="{% static "assets/images/twitter.png"%}" alt="" width=30 height=30></h2>
        <div class="twitter-feed">

<a class="twitter-timeline" data-width="500" data-height="500" data-theme="light" data-link-color="#26A9E0" href="https://twitter.com/oshelpcommunity">Tweets by oshelpcommunity</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
      </div>

      <div class="col-sm-4">
		  <h2>Upcoming Sessions <!-- <img src=" class="img-circle" width=30 height=30> -->
</h2>
        <!-- EventBrite widget -->
<div style="width:195px; text-align:center;" ><iframe  src="https://www.eventbrite.com/calendar-widget?eid=33954516874" frameborder="0" height="377" width="195" marginheight="0" marginwidth="0" scrolling="no" allowtransparency="true"></iframe><div style="font-family:Helvetica, Arial; font-size:12px; padding:10px 0 5px; margin:2px; width:195px; text-align:center;" ><a class="powered-by-eb" style="color: #ADB0B6; text-decoration: none;" target="_blank" href="http://www.eventbrite.com/">Powered by Eventbrite</a></div></div>
      </div>

    </div>

  </div>
  <div class="container">

    <!-- FOOTER -->
    <footer>
      <div class="row">
          <div class="col-sm-3">
              <p>&copy; 2017 OSHC</p>
          </div>
          <div class="col-sm-6">
              <a href=" https://github.com/OpenSourceHelpCommunity"><i class="fa fa-github" style="font-size:30px;padding-right:8px;"></i></a>
              <a href="https://twitter.com/oshelpcommunity"><i class="fa fa-twitter" style="font-size:30px;padding-right:8px;"></i></a>
              <a href="https://www.facebook.com/opensourcehelpcommunity/"><i class="fa fa-facebook" style="font-size:30px;padding-right:8px;"></i></a>
          </div>
          <div class="col-sm-3">
              <p><a href="#">Back to top</a></p>
          </div>

      </div>


    </footer>
  </div>
{% endblock %}